import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './font.css';
import './globals.css';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import { GlobalProvider } from './context/GlobalContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Icon digital ', 
	description: 'Generated by icon digital',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<ToastContainer position='top-right' />
				<GlobalProvider>{children}</GlobalProvider>
			</body>
		</html>
	);
}
